[package]
name = "slog"
version = "0.5.0"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Structured, composable logging for Rust"
keywords = ["log", "logging", "structured", "hierarchical"]
license = "MPL-2.0"
documentation = "https://dpc.github.io/slog-rs/"
homepage = "https://github.com/dpc/slog-rs"
repository = "https://github.com/dpc/slog-rs"
readme = "README.md"


[workspace]

[dependencies]
crossbeam = "0.2.9"
chrono = "0.2.22"
rustc-serialize = "0.3.19"

[dev-dependencies]
slog-json = { version = "0.5.0", path = "extra/json" }
slog-term = { version = "0.5.0", path = "extra/term" }
slog-stdlog = { version = "0.5.0", path = "extra/stdlog" }
slog-syslog = { version = "0.5.0", path = "extra/syslog" }
slog-bunyan = { version = "0.5.0", path = "extra/bunyan" }
log = "0.3.6"
