[package]
name = "slog"
version = "0.6.0"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Structured, composable logging for Rust"
keywords = ["log", "logging", "structured", "hierarchical"]
license = "MPL-2.0"
documentation = "https://dpc.github.io/slog-rs/"
homepage = "https://github.com/dpc/slog-rs"
repository = "https://github.com/dpc/slog-rs"
readme = "README.md"

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false

[workspace]

[dependencies]
crossbeam = "0.2.9"
chrono = "0.2.22"
rustc-serialize = "0.3.19"
error-chain = "0.2.1"

[dev-dependencies]
slog-json = { path = "crates/json" }
slog-term = { path = "crates/term" }
slog-stdlog = { path = "crates/stdlog" }
slog-syslog = { path = "crates/syslog" }
slog-bunyan = { path = "crates/bunyan" }
log = "0.3.6"
